# Generated by Django 2.2.1 on 2019-06-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='Booking',
        ),
    ]
